crossing time slots
akarzhaneuski/exadel_sandbox pull request #104
Opened 2021-05-24 15:36 UTC by SaranchukVadym

2021-05-24 15:48 UTC, akarzhaneuski requested changes

2021-05-24 15:48 UTC, akarzhaneuski commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/service/impl/EmployeeServiceImpl.java
> +            int compareValue = latestEmployeeTime.compareTo(timeDto.getDateTime());
Why not ```latestEmployeeTime.equals(timeDto.getDateTime())``` here?

2021-05-24 15:59 UTC, SaranchukVadym commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/service/impl/EmployeeServiceImpl.java
> +            int compareValue = latestEmployeeTime.compareTo(timeDto.getDateTime());
because equals return just boolean, when we need to know our value will less, more or the same

2021-05-25 07:10 UTC, akarzhaneuski approved these changes

2021-05-25 07:10 UTC, merged