Added controllers: StatusController , StatusHistoryController
akarzhaneuski/exadel_sandbox pull request #17
Opened 2021-04-01 09:35 UTC by DanilBut

2021-04-08 15:00 UTC, akarzhaneuski requested changes

2021-04-08 15:00 UTC, akarzhaneuski commented on sandbox-backend/build.gradle
> +    implementation group: 'javax.validation', name: 'validation-api', version: '2.0.1.Final'
https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-dependency-versions.html#dependency-versions
Don't specify versions for dependencies from this table manually. We use gradle boot plugin that will provide defauls. In case of boot versions upgrade migration process will be more easy with default versions

2021-04-08 15:00 UTC, akarzhaneuski commented on sandbox-web/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
We already have org.springframework.boot:spring-boot-starter-data-jpa dependency, don't need to add duplicate

2021-04-09 13:36 UTC, DanilBut commented on sandbox-web/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
Fixed

2021-04-09 13:36 UTC, DanilBut commented on sandbox-backend/build.gradle
> +    implementation group: 'javax.validation', name: 'validation-api', version: '2.0.1.Final'
Okey, fixed

2021-04-13 13:44 UTC, akarzhaneuski approved these changes

2021-04-13 13:44 UTC, merged