Dto in feedback candidate event
akarzhaneuski/exadel_sandbox pull request #20
Opened 2021-04-06 07:14 UTC by Aliaksei-Halkin

2021-04-08 15:06 UTC, akarzhaneuski requested changes

2021-04-08 15:06 UTC, akarzhaneuski commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/entity/CandidateEventEntity.java
> +import jdk.jfr.Event;
Strange import. Please optimize import (Ctrl + Shift + O hotkey in Idea)

2021-04-08 17:54 UTC, Aliaksei-Halkin commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/entity/CandidateEventEntity.java
> +import jdk.jfr.Event;
You are right! It isn't first time(

2021-04-09 15:46 UTC, Aliaksei-Halkin commented
Look at class CandidateEventServiceImpl, method "save": candidateEventEntity.setCandidates((List<CandidateEntity>) candidateEntity);
I am thinking now, maybe I need to add to CandidateEventEntity method add (to add every CandidateEntity to List)... I don't sure

2021-04-13 13:47 UTC, akarzhaneuski approved these changes

2021-04-13 15:19 UTC, merged