Added RSQL feature, also corrected validation error responses
akarzhaneuski/exadel_sandbox pull request #22
Opened 2021-04-08 06:48 UTC by RussellSk

2021-04-08 15:13 UTC, akarzhaneuski requested changes

2021-04-08 15:13 UTC, akarzhaneuski commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/configuration/ErrorHandlingControllerAdvice.java
> +class ErrorHandlingControllerAdvice {
Good approach to decorate exceptions! Just small note than class and methods should be public in ```@ControllerAdvice ```, package private might fail in some cases

2021-04-08 15:55 UTC, ikantsevich approved these changes

2021-04-09 06:01 UTC, RussellSk commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/configuration/ErrorHandlingControllerAdvice.java
> +class ErrorHandlingControllerAdvice {
Fixed access modifier. Thank you for advice

2021-04-09 07:05 UTC, ikantsevich commented on sandbox-web/src/main/java/com/exadel/team2/sandbox/controller/EmployeeController.java
> +            Node rootNode = new RSQLParser().parse(search);
Yes

2021-04-09 09:50 UTC, RussellSk commented on sandbox-web/src/main/java/com/exadel/team2/sandbox/controller/EmployeeController.java
> +            Node rootNode = new RSQLParser().parse(search);
Thank you!

2021-04-09 10:42 UTC, RussellSk commented on sandbox-web/src/main/java/com/exadel/team2/sandbox/controller/EmployeeController.java
> +            Node rootNode = new RSQLParser().parse(search);
Done. Moved RSQL logic from Controller to Service

2021-04-13 13:47 UTC, akarzhaneuski approved these changes

2021-04-13 15:23 UTC, merged