Handling exception, rsql and pagination for candidate, interviewTime and resume
akarzhaneuski/exadel_sandbox pull request #29
Opened 2021-04-13 13:32 UTC by SaranchukVadym

2021-04-13 14:25 UTC, akarzhaneuski requested changes

2021-04-13 14:25 UTC, akarzhaneuski commented on sandbox-web/src/main/resources/application.properties
> -logging.level.org.hibernate.SQL=DEBUG
For local its ok, but please don't commit this change. For prod branch debug logging is redundant

2021-04-14 05:10 UTC, SaranchukVadym commented on sandbox-web/src/main/resources/application.properties
> -logging.level.org.hibernate.SQL=DEBUG
corrected

2021-04-14 05:10 UTC, SaranchukVadym commented on sandbox-web/src/main/resources/application.properties
> -logging.level.org.hibernate.SQL=DEBUG
corrected

2021-04-14 11:03 UTC, closed without merging