Added liquibase script: status, status_history
akarzhaneuski/exadel_sandbox pull request #3
Opened 2021-03-26 14:48 UTC by DanilBut

2021-03-29 14:25 UTC, Clasker1 approved these changes
Looks good

2021-03-29 14:27 UTC, Clasker1 requested changes
Don't see any db.changelog-master.yaml  includes for migrations. Does it work on your local env?

2021-03-29 16:44 UTC, DanilBut commented
> Don't see any db.changelog-master.yaml includes for migrations. Does it work on your local env?

Yeah, it works

2021-03-30 09:17 UTC, akarzhaneuski requested changes

2021-03-30 09:17 UTC, akarzhaneuski commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/entity/Status.java
> +@Table(name = "STATUS", schema = "sandbox")
Please don't use schema in code, we have it in application configuration. It might be useful to use different schemas per different envs and configuration should be complicated

2021-03-30 09:17 UTC, akarzhaneuski commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/entity/Status.java
> +@NoArgsConstructor
By default we need only @Data annotation, it will generated setters/getters, equals/hashCode, required arg constructors. Remove unused annotations

2021-03-30 09:17 UTC, akarzhaneuski commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/entity/StatusHistory.java
> +@NoArgsConstructor
Remove unused annotations

2021-03-30 09:17 UTC, akarzhaneuski commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/entity/StatusHistory.java
> +@Table(name = "STATUS_HISTORY", schema = "sandbox")
Remove schema param

2021-03-30 09:17 UTC, akarzhaneuski commented on sandbox-backend/src/main/resources/db/changelog/changes/2021.03.26_create_table_candidate_event_halkin.yaml
> +      preConditions:
Some unrelated with PR changes, may be bad merge?

2021-03-30 09:17 UTC, akarzhaneuski commented on sandbox-backend/src/main/resources/db/changelog/changes/2021.03.26_create_table_feedback_halkin.yaml
> +      preConditions:
same here

2021-03-30 09:39 UTC, DanilBut commented on sandbox-backend/src/main/resources/db/changelog/changes/2021.03.26_create_table_candidate_event_halkin.yaml
> +      preConditions:
Yes! Fixed

2021-03-30 09:39 UTC, DanilBut commented on sandbox-backend/src/main/resources/db/changelog/changes/2021.03.26_create_table_feedback_halkin.yaml
> +      preConditions:
Fixed

2021-03-30 09:52 UTC, akarzhaneuski approved these changes

2021-03-30 09:52 UTC, merged