Global exception handler
akarzhaneuski/exadel_sandbox pull request #30
Opened 2021-04-13 16:07 UTC by VadimBlagiy

This is duplicate my branch "Added feature rsql and started to make GlobalExceptionHandler"

2021-04-13 18:23 UTC, akarzhaneuski requested changes

2021-04-13 18:23 UTC, akarzhaneuski commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/exceptions/GlobalExceptionHandler.java
> +    public ResponseEntity<IncorrectData> handlerException (NoSuchException exception) {
Please merge this with ``` ErrorHandlingControllerAdvice ``` in master

2021-04-13 18:23 UTC, akarzhaneuski commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/service/impl/ImageServiceImpl.java
> +        ImageEntity imageRemove = imageDAO.findById(id)
Possible, but i would replace with 
``` 
if ( !imageDAO.existsById()) {
    throw new NoSuchException('...');
}
```
Same for all places where we want to check if object exists in database

2021-04-13 18:33 UTC, VadimBlagiy commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/exceptions/GlobalExceptionHandler.java
> +    public ResponseEntity<IncorrectData> handlerException (NoSuchException exception) {
ok

2021-04-13 18:41 UTC, VadimBlagiy commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/service/impl/ImageServiceImpl.java
> +        ImageEntity imageRemove = imageDAO.findById(id)
Thanks! I will!

2021-04-14 07:10 UTC, akarzhaneuski requested changes

2021-04-14 07:10 UTC, akarzhaneuski commented on sandbox-web/build.gradle
> +    implementation group: 'cz.jirutka.rsql', name: 'rsql-parser', version: '2.1.0'
We already have this dependency ``` implementation 'cz.jirutka.rsql:rsql-parser:2.1.0' ```, this line should be removed

2021-04-14 07:16 UTC, VadimBlagiy commented on sandbox-web/build.gradle
> +    implementation group: 'cz.jirutka.rsql', name: 'rsql-parser', version: '2.1.0'
Ok!

2021-04-14 07:25 UTC, akarzhaneuski approved these changes

2021-04-14 07:26 UTC, merged