added check isEmpty
akarzhaneuski/exadel_sandbox pull request #37
Opened 2021-04-15 17:49 UTC by Aliaksei-Halkin

2021-04-15 20:03 UTC, akarzhaneuski requested changes

2021-04-15 20:03 UTC, akarzhaneuski commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/service/impl/CandidateEventServiceImpl.java
> +        if(search.isEmpty()) {
Bad code formatting => bad readability. Please reformat code with Ctrl + Alt + L  hothey

2021-04-15 20:03 UTC, akarzhaneuski commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/service/impl/InterviewFeedbackServiceImpl.java
> +        if(search.isEmpty()){
And here please

2021-04-15 21:30 UTC, Aliaksei-Halkin commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/service/impl/CandidateEventServiceImpl.java
> +        if(search.isEmpty()) {
I forgot to do it( Done!

2021-04-15 21:31 UTC, Aliaksei-Halkin commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/service/impl/InterviewFeedbackServiceImpl.java
> +        if(search.isEmpty()){
done

2021-04-16 13:40 UTC, akarzhaneuski approved these changes

2021-04-16 13:40 UTC, merged