Modify candidate table help of yaml format
akarzhaneuski/exadel_sandbox pull request #54
Opened 2021-04-26 14:48 UTC by SaranchukVadym

2021-04-26 14:54 UTC, ikantsevich requested changes

2021-04-26 14:54 UTC, ikantsevich commented on sandbox-backend/src/main/resources/db/changelog/changes/2021.04.17_run_fix_table_candidate.yaml
> +      id: run-fix-table-candidate
We can't modify existing changesets we should create a new one

2021-04-26 14:54 UTC, ikantsevich commented on sandbox-backend/src/main/resources/db/changelog/changes/24.04.2021_modify_candidate_table.yaml
> +        onFail: CONTINUE
On fail should be MARK_RAN

2021-04-26 14:54 UTC, ikantsevich commented on sandbox-backend/src/main/resources/db/changelog/changes/24.04.2021_modify_candidate_table.yaml
> +        tableExists:
columnExists precondition is enough here, tableExists not need

2021-04-26 14:54 UTC, ikantsevich commented on sandbox-backend/src/main/resources/db/changelog/changes/24.04.2021_modify_candidate_table.yaml
> +        tableExists:
the same

2021-04-26 15:08 UTC, SaranchukVadym commented on sandbox-backend/src/main/resources/db/changelog/changes/2021.04.17_run_fix_table_candidate.yaml
> +      id: run-fix-table-candidate
corrected

2021-04-26 15:12 UTC, SaranchukVadym commented on sandbox-backend/src/main/resources/db/changelog/changes/24.04.2021_modify_candidate_table.yaml
> +        tableExists:
corrected

2021-04-26 15:12 UTC, SaranchukVadym commented on sandbox-backend/src/main/resources/db/changelog/changes/24.04.2021_modify_candidate_table.yaml
> +        tableExists:
corrected

2021-04-26 15:40 UTC, SaranchukVadym commented on sandbox-backend/src/main/resources/db/changelog/changes/24.04.2021_modify_candidate_table.yaml
> +        onFail: CONTINUE
corrected

2021-04-27 06:49 UTC, ikantsevich approved these changes

2021-04-27 06:49 UTC, merged