the beginning
akarzhaneuski/exadel_sandbox pull request #6
Opened 2021-03-29 20:11 UTC by Aliaksei-Halkin

2021-03-30 10:01 UTC, akarzhaneuski requested changes

2021-03-30 10:01 UTC, akarzhaneuski commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/entity/InterviewFeedbackEntity.java
> +public class InterviewFeedbackEntity {
Need to finish this entity, ``` feedback ```, ``` createdAt ```, ``` updatedAt ``` fields could be added here

2021-03-30 22:19 UTC, Aliaksei-Halkin commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/entity/InterviewFeedbackEntity.java
> +public class InterviewFeedbackEntity {
added

2021-03-31 06:45 UTC, ikantsevich commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/entity/InterviewFeedbackEntity.java
> +    private int id;
Better use Long instead of int for id

2021-03-31 08:23 UTC, Aliaksei-Halkin commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/entity/InterviewFeedbackEntity.java
> +    private int id;
replaced all "int id" on "long id"

2021-03-31 09:55 UTC, ikantsevich commented
Please add controllers and services

2021-03-31 21:28 UTC, Aliaksei-Halkin commented
I added controllers and services, changed entity, but I'm not sure in tables' relationships. And app finished with exit cose 1

2021-04-06 07:11 UTC, closed without merging

2021-04-06 07:12 UTC, Aliaksei-Halkin commented
opened new PR