Entity blagiy
akarzhaneuski/exadel_sandbox pull request #7
Opened 2021-03-29 21:52 UTC by VadimBlagiy

2021-03-30 10:04 UTC, akarzhaneuski requested changes

2021-03-30 10:04 UTC, akarzhaneuski commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/entity/EventEntity.java
> +@NoArgsConstructor
Only ``` @Data ``` annotation is required here. Another are optional, please check lombok features https://projectlombok.org/features/all and remove unused annotations

2021-03-30 10:04 UTC, akarzhaneuski commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/entity/EventEntity.java
> +    private Date evStartDate;
LocalDateTime will be better here

2021-03-30 10:04 UTC, akarzhaneuski commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/entity/EventEntity.java
> +    private Date evDeadline;
LocalDateTime

2021-03-30 10:04 UTC, akarzhaneuski commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/entity/EventTypeEntity.java
> +@NoArgsConstructor
Review annotations here

2021-03-30 16:29 UTC, VadimBlagiy commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/entity/EventEntity.java
> +@NoArgsConstructor
Done

2021-03-30 16:30 UTC, VadimBlagiy commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/entity/EventEntity.java
> +    private Date evStartDate;
Done

2021-03-30 16:30 UTC, VadimBlagiy commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/entity/EventEntity.java
> +    private Date evDeadline;
Done

2021-03-30 16:31 UTC, VadimBlagiy commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/entity/EventTypeEntity.java
> +@NoArgsConstructor
Done

2021-03-31 06:43 UTC, ikantsevich approved these changes

2021-03-31 08:30 UTC, akarzhaneuski approved these changes

2021-03-31 08:31 UTC, merged