Added script, refactored services
akarzhaneuski/exadel_sandbox pull request #77
Opened 2021-05-03 15:14 UTC by DanilBut

2021-05-04 06:56 UTC, ikantsevich approved these changes

2021-05-04 06:56 UTC, ikantsevich commented on sandbox-backend/src/main/resources/db/changelog/changes/2021.03.05_dropNotNullConstraint_status_history.yaml
> +      author: butenko
please add precondition

2021-05-04 06:57 UTC, ikantsevich requested changes

2021-05-04 06:57 UTC, ikantsevich commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/entity/StatusHistory.java
>      private LocalDateTime createdAt;
Why we should remove notnull?

2021-05-04 11:05 UTC, DanilBut commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/entity/StatusHistory.java
>      private LocalDateTime createdAt;
returned it back

2021-05-04 11:05 UTC, DanilBut commented on sandbox-backend/src/main/resources/db/changelog/changes/2021.03.05_dropNotNullConstraint_status_history.yaml
> +      author: butenko
corrected

2021-05-05 05:19 UTC, ikantsevich commented on sandbox-backend/src/main/resources/db/changelog/changes/2021.03.05_dropNotNullConstraint_status_history.yaml
> +      author: butenko
If we added default value for this column this changeset not need

2021-05-05 07:05 UTC, ikantsevich approved these changes

2021-05-05 07:05 UTC, merged