Saranchuk table scripts
akarzhaneuski/exadel_sandbox pull request #9
Opened 2021-03-31 13:56 UTC by SaranchukVadym

was corrected all mistakes in scripts

2021-03-31 14:02 UTC, akarzhaneuski requested changes

2021-03-31 14:29 UTC, SaranchukVadym commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/controller/Controller.java
> +package com.exadel.team2.sandbox.controller;public class Controller {
I don't know why it added so

2021-03-31 14:32 UTC, SaranchukVadym commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/service/impl/CandidateServiceImpl.java
> +package com.exadel.team2.sandbox.service.impl;public class CandidateServiceImpl {
implements or use annotation @Service?

2021-04-06 06:19 UTC, VadimBlagiy commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/controller/ControllerInterviewTime.java
> +    @PutMapping
(value = "/{id}")   need add

2021-04-06 06:21 UTC, VadimBlagiy commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/controller/ControllerResume.java
> +    @PutMapping
put id

2021-04-06 06:37 UTC, ikantsevich commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/dto/CandidateUpdateDTO.java
> +    private Long id;
Id can't be updated

2021-04-06 06:37 UTC, ikantsevich commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/dto/CandidateUpdateDTO.java
> +    private String skype;
All these fields can't be @NotNull cause we can update only lastName or firstName without any other fields

2021-04-06 06:37 UTC, ikantsevich commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/dto/InterviewTimeUpdateDTO.java
> +    private Long itmId;
We can't update id

2021-04-06 06:37 UTC, ikantsevich commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/dto/ResumeUpdateDTO.java
> +    private Long id;
the same

2021-04-06 06:37 UTC, ikantsevich commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/entity/CandidateEntity.java
> +//    private Collection<Event> events;
Why it is commented? in my mind we already have EventEntity

2021-04-06 06:37 UTC, ikantsevich commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/mapper/Release.java
> +public class Release implements Convertor {
Please rename this class

2021-04-06 06:37 UTC, ikantsevich commented on sandbox-backend/src/main/resources/db/changelog/changes/20210326_create_table_employee.yaml
> -databaseChangeLog:
We can't remove changeset, please return it back

2021-04-06 06:37 UTC, ikantsevich commented on sandbox-backend/src/main/resources/db/changelog/changes/20210329_drop_demo_table.yaml
> -  - changeSet:
the same

2021-04-06 06:37 UTC, ikantsevich commented on sandbox-backend/src/main/resources/db/changelog/db.changelog-master.yaml
> +#      file: db/changelog/changes/20210329_drop_demo_table.yaml
why it is commented?

2021-04-07 07:10 UTC, akarzhaneuski commented on sandbox-backend/build.gradle
> +    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-web', version: '2.4.3'
We already have spring-boot-started dependency here, need to remove

2021-04-07 07:11 UTC, akarzhaneuski commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/controller/ControllerCandidate.java
> +public class ControllerCandidate {
Move rest controllers to sandbox-web module. Here we should keep business logic (services) and DAO

2021-04-07 07:12 UTC, akarzhaneuski commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/controller/ControllerInterviewTime.java
> +public class ControllerInterviewTime {
Move to sandbox-web as well

2021-04-07 07:12 UTC, akarzhaneuski commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/controller/ControllerResume.java
> +public class ControllerResume {
Move to sandbox-web

2021-04-07 07:13 UTC, akarzhaneuski commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/dao/InterviewTimeDAO.java
> +public interface InterviewTimeDAO extends JpaRepository<InterviewTimeEntity, Long> {
Need to add ```@Repository```

2021-04-07 07:13 UTC, akarzhaneuski commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/dao/ResumeDAO.java
> +public interface ResumeDAO extends JpaRepository<ResumeEntity, Long> {
```@Repository```

2021-04-07 07:22 UTC, akarzhaneuski commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/entity/ResumeEntity.java
> +public class ResumeEntity {
Need to use upper case. On linux machines it will not work

2021-04-07 07:23 UTC, akarzhaneuski commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/service/InterviewTimeServer.java
> +public interface InterviewTimeServer {
Rename to ``` InterviewTimeService ```

2021-04-07 07:24 UTC, akarzhaneuski commented on sandbox-backend/src/main/resources/db/changelog/changes/2021.03.26_create_table_blagiy.yml
> +                  type: INT UNSIGNED
Don't modify existing changeset, create new migration instead. And why do you use unsigned int for ids? At another tables we use just int. Need to be consistent in all DB schema, lets use just int in your tables as well

2021-04-07 07:27 UTC, akarzhaneuski commented on sandbox-backend/src/main/resources/db/changelog/db.changelog-master.yaml
> -      file: db/changelog/changes/20210330_load_data.yaml
Looks like wrong change. We should not change order for existing migrations. Keep all previous migrations as is, and just add yours at the end of file

2021-04-07 07:29 UTC, akarzhaneuski commented on sandbox-web/build.gradle
> +    implementation 'junit:junit:4.12'
Don't specify versions manually for common dependencies. Let boot plugin to provide defaults

2021-04-07 08:56 UTC, SaranchukVadym commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/controller/ControllerInterviewTime.java
> +    @PutMapping
corrected

2021-04-07 08:56 UTC, SaranchukVadym commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/controller/ControllerResume.java
> +    @PutMapping
corrected

2021-04-07 08:56 UTC, SaranchukVadym commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/dto/CandidateUpdateDTO.java
> +    private Long id;
corrected

2021-04-07 08:56 UTC, SaranchukVadym commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/dto/CandidateUpdateDTO.java
> +    private String skype;
corrected

2021-04-07 08:56 UTC, SaranchukVadym commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/dto/InterviewTimeUpdateDTO.java
> +    private Long itmId;
corrected

2021-04-07 08:56 UTC, SaranchukVadym commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/dto/ResumeUpdateDTO.java
> +    private Long id;
corrected

2021-04-07 08:57 UTC, SaranchukVadym commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/mapper/Release.java
> +public class Release implements Convertor {
corrected

2021-04-07 08:57 UTC, SaranchukVadym commented on sandbox-backend/src/main/resources/db/changelog/changes/20210326_create_table_employee.yaml
> -databaseChangeLog:
corrected

2021-04-07 08:57 UTC, SaranchukVadym commented on sandbox-backend/src/main/resources/db/changelog/changes/20210329_drop_demo_table.yaml
> -  - changeSet:
corrected

2021-04-07 08:57 UTC, SaranchukVadym commented on sandbox-backend/src/main/resources/db/changelog/db.changelog-master.yaml
> +#      file: db/changelog/changes/20210329_drop_demo_table.yaml
corrected

2021-04-07 09:58 UTC, SaranchukVadym commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/dao/InterviewTimeDAO.java
> +public interface InterviewTimeDAO extends JpaRepository<InterviewTimeEntity, Long> {
corrected

2021-04-07 09:58 UTC, SaranchukVadym commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/dao/ResumeDAO.java
> +public interface ResumeDAO extends JpaRepository<ResumeEntity, Long> {
corrected

2021-04-07 09:59 UTC, SaranchukVadym commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/entity/ResumeEntity.java
> +public class ResumeEntity {
corrected

2021-04-07 10:00 UTC, SaranchukVadym commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/service/InterviewTimeServer.java
> +public interface InterviewTimeServer {
corrected

2021-04-07 10:02 UTC, SaranchukVadym commented on sandbox-backend/src/main/resources/db/changelog/db.changelog-master.yaml
> -      file: db/changelog/changes/20210330_load_data.yaml
corrected

2021-04-07 10:04 UTC, SaranchukVadym commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/controller/ControllerResume.java
> +public class ControllerResume {
corrected

2021-04-07 10:04 UTC, SaranchukVadym commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/controller/ControllerInterviewTime.java
> +public class ControllerInterviewTime {
corrected

2021-04-07 10:05 UTC, SaranchukVadym commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/controller/ControllerCandidate.java
> +public class ControllerCandidate {
corrected

2021-04-07 12:52 UTC, SaranchukVadym commented on sandbox-backend/src/main/resources/db/changelog/changes/2021.03.26_create_table_blagiy.yml
> +                  type: INT UNSIGNED
corrected

2021-04-07 12:58 UTC, SaranchukVadym commented on sandbox-web/build.gradle
> +    implementation 'junit:junit:4.12'
corrected

2021-04-07 12:59 UTC, SaranchukVadym commented on sandbox-backend/build.gradle
> +    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-web', version: '2.4.3'
corrected

2021-04-07 12:59 UTC, SaranchukVadym commented on sandbox-backend/build.gradle
> +    implementation group: 'org.modelmapper', name: 'modelmapper', version: '2.4.0'
corrected

2021-04-07 13:00 UTC, SaranchukVadym commented on sandbox-backend/build.gradle
> +    testImplementation group: 'junit', name: 'junit', version: '4.13.2'
corrected

2021-04-08 14:51 UTC, akarzhaneuski approved these changes

2021-04-08 14:52 UTC, merged