Added sender email
akarzhaneuski/exadel_sandbox pull request #94
Opened 2021-05-13 11:13 UTC by DanilBut

2021-05-13 11:33 UTC, akarzhaneuski requested changes

2021-05-13 11:33 UTC, akarzhaneuski commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/configuration/EmailConfig.java
> +        JavaMailSenderImpl mailSender = new JavaMailSenderImpl();
``` JavaMailSender mailSender = new JavaMailSenderImpl(); ```
see https://habr.com/ru/post/83269/ as a reference

2021-05-13 11:33 UTC, akarzhaneuski commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/service/impl/CandidateServiceImpl.java
> +            exception.printStackTrace();
Bad exception handling, its better to log exception with message like:
``` log.errror("Error during email sending {}", e.getMessage(), e); ```

2021-05-13 11:33 UTC, akarzhaneuski commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/service/impl/InterviewTimeServiceImpl.java
> +            e.printStackTrace();
same about logs

2021-05-13 11:33 UTC, akarzhaneuski commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/service/impl/SendEmailServiceImpl.java
> +            e.printStackTrace();
same about logs

2021-05-15 10:15 UTC, DanilBut commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/configuration/EmailConfig.java
> +        JavaMailSenderImpl mailSender = new JavaMailSenderImpl();
i have moved the config to application.properties

2021-05-15 10:15 UTC, DanilBut commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/service/impl/CandidateServiceImpl.java
> +            exception.printStackTrace();
corrected

2021-05-15 10:15 UTC, DanilBut commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/service/impl/InterviewTimeServiceImpl.java
> +            e.printStackTrace();
corrected

2021-05-15 10:15 UTC, DanilBut commented on sandbox-backend/src/main/java/com/exadel/team2/sandbox/service/impl/SendEmailServiceImpl.java
> +            e.printStackTrace();
corrected

2021-05-18 12:11 UTC, akarzhaneuski approved these changes

2021-05-18 12:11 UTC, merged